### ISSUE TITLE
Unable to rejoin full game properly

### ISSUE THREAD

**Issue by matthewfcarlson** [BYUCS340/Catan#40]
It looks like we aren't able to join a game with 4 players in it already. It looks like it's assigning negative numbers for player index to the players

**Comment by eaglewyng** [comment]
As in, we can't rejoin a game with 4 players?

**Comment by matthewfcarlson** [comment]
Correct. It joins the game but none of the controllers activate properly. It just sits there doing nothing

**Comment by matthewfcarlson** [comment]
It looks like this was fixed but I'm not sure why or what happened.
