### ISSUE TITLE
Players start out with random resources

### ISSUE THREAD

**Issue by eaglewyng** [BYUCS340/Catan#47]

**Comment by eaglewyng** [comment]
This may not actually be a bug

**Comment by matthewfcarlson** [comment]
True. It's definitely coming from the server.

**Comment by eaglewyng** [comment]
Confirmed not a bug via the Catan handbook, https://students.cs.byu.edu/~cs340ta/winter2016/group_project/Catan_Rules.pdf. Apparently, players start out with some resources.
