### ISSUE TITLE
End Game doesn't work with multiplayer

### ISSUE THREAD

**Issue by eaglewyng** [BYUCS340/Catan#50]
The winner doesn't get a winning dialog box and everyone else is a winner

**Comment by eaglewyng** [comment]
Fixed a bug where the WinnerIndex was being compared to the WinnerIndex in the client in order to see which dialog box should appear. Also made the pointscontroller listen to everything.

**Comment by matthewfcarlson** [comment]
Points controller now listens to state and score

**Comment by eaglewyng** [comment]
It works beautifully now. YAY
