### ISSUE TITLE
Resource Bar isn't updating properly

### ISSUE THREAD

**Issue by tunadude09** [BYUCS340/Catan#61]
After accepting a trade, the resources are updated server side then refresh from server is called on the game model proxy. The model updates eventually but the resource bar never updates until you restart the client or you go to your next turn. John thinks it might be a Bank problem? Hard to say

**Comment by matthewfcarlson** [comment]
It does update when you play a road so I'll look into why.

**Comment by matthewfcarlson** [comment]
Alright I put better checking in for when resources update. We should do better testing and see if it fixes it.
